apiVersion: v2
name: venafi-kubernetes-agent
description: |-
  The Venafi Kubernetes Agent connects your Kubernetes or Openshift cluster to the Venafi Control Plane.
type: application
version: 0.0.0
appVersion: "v0.0.0"
home: https://github.com/jetstack/jetstack-secure
maintainers:
- name: JSCP and CRE Team
  email: tls-protect-for-kubernetes@jetstack.io
  url: https://platform.jetstack.io/documentation
sources:
- https://github.com/jetstack/jetstack-secure
