# if changing this name, also update promotion.yaml
name: release-tag

on:
  push:
    tags:
      - v*

jobs:
  docker_tag:
    name: docker_build
    runs-on: ubuntu-20.04
    container:
      image: docker:20.10.5
      options: -t
    # Setting up dind service container
    services:
      docker:
        image: docker:20.10.5-dind
        env:
          DOCKER_DRIVER: overlay
          DOCKER_HOST: tcp://localhost:2375
    steps:
    - name: Install Tools
      run: apk add --update make git jq rsync curl
    - uses: actions/checkout@v2.3.3
    - name: Capture tag in env
      run: echo "TAG_LABEL=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: image=moby/buildkit:master
    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Tag latest
      run: make create-docker-image-tag NEW_TAG=latest
    - name: Tag with git tag
      run: make create-docker-image-tag NEW_TAG=${{ env.TAG_LEVEL }}
